server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: warn

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3543/loki/api/v1/push

scrape_configs:
  - job_name: anisakys
    static_configs:
      - targets:
          - localhost
        labels:
          job: anisakys
          service: anisakys-api
          __path__: /var/log/anisakys/*.log

    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) - (?P<logger>\S+) - (?P<level>[A-Z]+) - (?P<message>.*)'
      - labels:
          level:
          logger:
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05"
          location: UTC
